In [ ]:
#Задание 1
import numpy as np
import random

a = np.arange(1, 10).reshape(3,3)
b = a * 2
print("Изначальный массив:")
print(a)
print("Массив после умножения на 2")
print(b)

final = np.where(b > 10, 0, b)
print("Конечный массив")
print(final)

Изначальный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Массив после умножения на 2
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Конечный массив
[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


In [ ]:
#Задание 2
import numpy as np

a = np.random.randint(1, 101, 20)
print("Полученный массив\n",  a)

delenie = a[a % 5 == 0]
print("Числа, делящиеся на 5\n",delenie)

a[a % 5 == 0] = -1
print("Обновленный массив\n",a)

Полученный массив
 [29 17 91 41 94  9 27 94 69 53  5 73 50 27 46 79 21 51 21 26]
Числа, делящиеся на 5
 [ 5 50]
Обновленный массив
 [29 17 91 41 94  9 27 94 69 53 -1 73 -1 27 46 79 21 51 21 26]


In [ ]:
#Задание 3
import numpy as np

a = np.random.randint(0, 51, 5)
b = np.random.randint(0, 51, 5)
print('Массив №1\n ', a)
print('Массив №2\n', b)

summa = np.concatenate((a, b))
print('Сумма массивов\n',summa)

pazd = np.split(summa, 2)
print('Разделенные массивы\n',pazd)

Массив №1
  [15 37 25 24  4]
Массив №2
 [ 3 36 16 33 45]
Сумма массивов
 [15 37 25 24  4  3 36 16 33 45]
Разделенные массивы
 [array([15, 37, 25, 24,  4]), array([ 3, 36, 16, 33, 45])]


In [ ]:
#Задание 4
import numpy as np

a = np.linspace(-10, 10, 50)
print('Полученный массив:\n',a)

summa = np.sum(a)
print('Сумма всех элементов:', summa)

positive_elements = a[a > 0]
psumm = np.sum(positive_elements)
print('Сумма положительных элементов:', psumm)

negative_element = a[a < 0]
nsumm = np.sum(negative_element)
print('Сумма отрицательных элементов:', nsumm)

Полученный массив:
 [-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]
Сумма всех элементов: 7.105427357601002e-15
Сумма положительных элементов: 127.55102040816328
Сумма отрицательных элементов: -127.55102040816327


In [ ]:
#Задание 5
import numpy as np

#Создание единичной матрицы
a = np.eye(4)
print('Созданная единичная матрица: \n',a)

#Создание диагональной матрицы
b = np.matrix([[5, 0, 0, 0], [0, 10, 0, 0], [0, 0, 15, 0], [0, 0, 0, 20]])
print('Созданная диагональная матрица: \n',b)

sumA = np.sum(a)
print('Сумма элементов единичной матрицы: ', sumA)

sumB = np.sum(b)
print('Сумма элементов диагональной матрицы: ', sumB)

if sumA == sumB:
  print('Суммы элементов матриц равны ')
elif sumA > sumB:
  print('Сумма элементов единичной матрицы больше суммы элементов диагональной матрицы')
else:
  print('Сумма элементов диагональной матрицы больше суммы элементов единичной матрицы')

Созданная единичная матрица: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Созданная диагональная матрица: 
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма элементов единичной матрицы:  4.0
Сумма элементов диагональной матрицы:  50
Сумма элементов диагональной матрицы больше суммы элементов единичной матрицы


In [ ]:
#Задание 6
import numpy as np

a = np.random.randint(1, 21, 9).reshape(3,3)
print('Первая созданная матрица:\n',a)

b = np.random.randint(1, 21, 9).reshape(3,3)
print('Вторая созданная матрица:\n',b)

summa = (a + b)
print('Сумма матриц:\n', summa)

paznost = np.subtract(a, b)
print('Разность матриц:\n',paznost)

proizv = a * b
print('Поэлементной умножение матриц: \n', proizv)

Первая созданная матрица:
 [[10  1  9]
 [ 4 14  9]
 [14  8  2]]
Вторая созданная матрица:
 [[ 7  3  2]
 [ 9  9  3]
 [20 13 11]]
Сумма матриц:
 [[17  4 11]
 [13 23 12]
 [34 21 13]]
Разность матриц:
 [[ 3 -2  7]
 [-5  5  6]
 [-6 -5 -9]]
Поэлементной умножение матриц: 
 [[ 70   3  18]
 [ 36 126  27]
 [280 104  22]]


In [ ]:
#Задание 7
import numpy as np

a = np.random.randint(1, 11, 6).reshape(2,3)
print('Первая созданная матрица:\n',a)

b = np.random.randint(1, 11, 6).reshape(3,2)
print('Вторая созданная матрица:\n',b)

result = np.dot(a, b)
print('Матричное умножение:\n', result)

Первая созданная матрица:
 [[6 3 1]
 [6 7 5]]
Вторая созданная матрица:
 [[3 6]
 [1 8]
 [8 2]]
Матричное умножение:
 [[ 29  62]
 [ 65 102]]


In [ ]:
#Задание 8
import numpy as np

a = np.random.randint(-100, 100, 9).reshape(3,3)
print('Cозданная матрица:\n',a)

opr = np.linalg.det(a)
print('Определитель созданной матрицы:', opr)

if opr != 0:
  obratn = np.linalg.inv(a)
  print('Обратная матрица:\n', obratn)
else:
  print('Матрица вырождена')

Cозданная матрица:
 [[ 88  26 -50]
 [-16  76  48]
 [-20  25 -68]]
Определитель созданной матрицы: -669631.9999999998
Обратная матрица:
 [[ 0.0095097  -0.00077356 -0.00753847]
 [ 0.0030584   0.01042961  0.00511326]
 [-0.00167256  0.00406193 -0.01060881]]


In [ ]:
#Задание 9
import numpy as np

a = np.random.randint(1, 51, 16).reshape(4,4)
print('Cозданная матрица:\n',a)

transonirovanie = np.transpose(a)
print('Транспонированная матрица:\n', transonirovanie)

sled = np.trace(a)
print('Cлед матрицы:', sled)

Cозданная матрица:
 [[23 49  3 34]
 [39  6  8 44]
 [ 8 44 45 38]
 [ 6 35 24 35]]
Транспонированная матрица:
 [[23 39  8  6]
 [49  6 44 35]
 [ 3  8 45 24]
 [34 44 38 35]]
Cлед матрицы: 109


In [ ]:
#Задание 10
import numpy as np

A = np.array([[2, 3, -1],
              [4, -1, 2],
              [-3, 5, 4]])

B = np.array([5, 6, -2])
x = np.linalg.solve(A, B)
print("Полученные корни х, y, z:\n",x)

Полученные корни х, y, z:
 [1.63963964 0.57657658 0.00900901]


In [ ]:
#Индивидуальное задание. Вариант 2
import numpy as np

# Определим матрицу коэффициентов A и вектор свободных членов b
A = np.array([[5, 2, 10],
              [2, 1, 3],
              [1, 0.5, 2]])

b = np.array([100, 30, 15])

# Метод Крамера
def cramer(A, b):
    n = A.shape[0]
    x = np.zeros(n)
    det_A = np.linalg.det(A)

    for i in range(n):
        # Создаем копию A и заменяем i-ый столбец на b
        Ai = A.copy()
        Ai[:, i] = b
        x[i] = np.linalg.det(Ai) / det_A

    return x

# Решение с помощью метода Крамера
solution_cramer = cramer(A, b)

# Решение с помощью матричного метода (обратная матрица)
solution_matrix_method = np.linalg.inv(A).dot(b)

# Решение с помощью np.linalg.solve
solution_np_linalg_solve = np.linalg.solve(A, b)

# Вывод результатов
print("Решение методом Крамера:", solution_cramer)
print("Решение матричным методом:", solution_matrix_method)
print("Решение с использованием np.linalg.solve:", solution_np_linalg_solve)

Решение методом Крамера: [ 40. -50.   0.]
Решение матричным методом: [ 40. -50.   0.]
Решение с использованием np.linalg.solve: [ 40. -50.   0.]
